server:
  port: 8002

grpc:
  port: 6002

service-c:
  host: localhost
  port: 6003

spring:
  application:
    name: service-b
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
  grpc:
    enabled: true
  http:
    enabled: true
  async:
    enabled: false
  log:
    slf4j:
      enabled: true
  reactor:
    enabled: false
  zipkin:
    base-url: http://localhost:9411/